version: "3.9"
services:
  database:
    ports:
      - ${PORT_DATABASE}:3306

  web:
    ports:
      - ${PORT_HTTP}:80

  phpmyadmin:
    ports:
      - ${PORT_PHPMYADMIN}:80

  node:
    command: npm run watch

  smtp:
    ports:
      - ${PORT_MAILDEV}:1080